import React from "react"
import FooterMenu from "./FooterMenu"
import { Link } from "gatsby"

const Footer = ({ menus }) => {

  return (
    <div>
      <div className="footer__wrapper">
        <footer className="footer">
          <FooterMenu menus={menus} />
          <p className="footer__copyrihgts tac">
            Copyright © 2019 DupliTrade Limited. All Rights Reserved Risk
            Warning Terms And Conditions Privacy Policy
          </p>
          <p className="footer__disc">
            <strong>Disclaimer:</strong> Trading foreign exchange (“forex”),
            commodity futures, options, contract for difference ("cfd") and
            spread betting on margin (the "investment products") carry a high
            level of risk, and may not be suitable for all investors. Before
            deciding to trade using the investment products you should carefully
            consider your monetary objectives, level of experience, and risk
            appetite. The possibility exists that you could sustain a loss of
            some or all of your deposited funds and therefore you should not
            speculate with capital that you cannot afford to lose. You should be
            aware of all the risks associated with the investment products, and
            seek advice from an independent advisor if you have any doubts. Past
            performance results are not necessarily indicative of future
            results. No representation is being made that any account will or is
            likely to achieve profits or losses similar to those shown. The
            performance results of the demonstration ("demo") account displayed
            on this website imitating real time transactions made by investors
            using the investment products in real accounts, do not guarantee
            that same results would have been achieved if you were to imitate
            the foregoing transactions in real time using a real account. In
            fact, there are frequently sharp differences between performance
            results using the demo account and performance results achieved by
            using any particular investment product and third party trading
            signals in real account, due to factors related to the involvement
            of your broker in the transaction and technical limitations and
            capabilities, which are not under the control of DupliTrade.
            Finally, there are numerous other factors related to the markets in
            general or to the implementation of any specific investment product
            and third party trading signal which cannot be fully accounted for
            by past performance results. Prospective clients should be
            particularly wary of placing undue reliance on past performance
            results and should not base their decision to use any investment
            product and/or any third party trading signal solely on the past
            performance presented. The investment products described herein have
            been developed for sophisticated traders who fully understand the
            nature and the scope of the risks that are associated with trading.
            Therefore, in making an investment decision, prospective clients
            must also rely on their own examination of the person or entity
            making the trading decisions and the terms of the advisory agreement
            including the merits and risks involved. You understand that there
            is no strategy provider or recommendation service that is free from
            the risk of loss. You also understand that the transfer of third
            party trading signals by the application to your brokers trading
            account, shall not in any event constitute the provision of
            investment services or advice by DupliTrade. In making a decision to
            follow a specific third party trading signal, account, portfolio
            and/or strategy, you have considered your entire financial situation
            including financial commitments and you understand that you could
            sustain significant losses in your account. DupliTrade does not
            imply or guarantee that you will make a profit and you agree that
            neither DupliTrade nor any of its officers, directors, employees,
            consultants, agents or affiliates will be held responsible for the
            performance of the trading signals generated by third parties and
            transferred by the application to your brokers trading account or
            trading losses in your account. If you do not agree with the terms
            of the disclaimer, please exit the website and do not use any of its
            investment products. (the terms of your and application shall have
            the meaning ascribed to them in the end user license agreement)
            Please refer to our Risk Warning for more detailed information.
          </p>
        </footer>
      </div>
      <h1 className="Button--blueBackgroundless">
        <Link to="/strategyProviders">Strategy Providers</Link>
      </h1>
      <h1 className="Button--blueBackgroundless">
        <Link to="/">Back Home</Link>
      </h1>
    </div>
  )
}

export default Footer


// c8526886-5a20-59ea-be0d-3eb97ae4a4b6